version: '2'

services:
  ui:
    restart: always
    build: ./client
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - '80:3000'
    depends_on:
      - api

  api:
    build: ./api
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
